name: Publish sfweb container to ghcr.io

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  pull_request:
    branches:
      - 'master'
  push:
    tags:
      - '*'
  workflow_dispatch: # pour être lancé à la main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    strategy:
      fail-fast: true
      matrix:
        env: [ preprod, production ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node tools
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - run: npm install --global yarn # mandatory with act
      - run: yarn install
      - run: npx vue-cli-service build --mode=${{ matrix.env }} --quiet
      - run: cp -r ./dist/* ./build-container

      - name: Build container image
        shell: bash
        run: |
          docker build --tag sfweb --build-arg app="." ./build-container

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha
          flavor: |
            latest=false
            suffix=-${{ matrix.env }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./build-container
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}